### ISSUE TITLE
tables not rendering

### ISSUE THREAD

**Issue by timeyyy** [pybuilder/pybuilder.github.io#23]
the tables in plugins.md are not rendering.

**Comment by jayvdb** [comment]
The section headings after the first table are also not rendering on http://pybuilder.github.io/documentation/plugins.html

**Comment by AlexeySanko** [comment]
Unfortunately, locally builded page from master is correct.
![image](https://user-images.githubusercontent.com/20610690/27027982-09a613ac-4f6c-11e7-96af-692548ea0edb.png)

Where could be problem? Version of jekyll?

**Comment by esc** [comment]
Hmmm, how do we fix this?

**Comment by esc** [comment]
I pushed an empty commit in an attempt have jekyll rebuild.

**Comment by esc** [comment]
The markdown parser was choking on tripple backticks, the following commit fixed it:

https://github.com/pybuilder/pybuilder.github.io/commit/86b4671e5a06e9b8f176417347fd15f038464028
