### ISSUE TITLE
Add to distutils_plugin information about cleaning

### ISSUE THREAD

**Issue by AlexeySanko** [pybuilder/pybuilder.github.io#37]
https://github.com/pybuilder/pybuilder/issues/421

Into distutils_plugin.py hardcoded ["clean", "--all"] for each distutils_commands. And we cannot use results of one step into next steps. We need to add information about it.

**Comment by AlexeySanko** [comment]
Do we need info about workaround?
https://github.com/pybuilder/pybuilder/issues/421#issuecomment-261287295

**Comment by esc** [comment]
closed via #38
